---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-sample
  namespace: test-deployments
spec:
  selector:
    matchLabels:
      app: nginx-deployment-sample
  replicas: 0
  template:
    metadata:
      labels:
        app: nginx-deployment-sample
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: test-deployments
spec:
  selector:
    app: nginx-deployment-sample
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
