apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: "{{ .Values.project_name }}-role"
    namespace: "{{ .Values.project_namespace }}"
  rules:
  - apiGroups:
    - "*"
    resources:
    - "*"
    verbs:
    - "*"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""