apiVersion: v1
kind: ResourceQuota
metadata:
  name: "{{ .Values.project_name }}-storagequota"
  namespace: "{{ .Values.project_namespace }}"
spec:
  hard:
    requests.storage: "{{ .Values.request_storage }}"
