apiVersion: batch/v1
kind: CronJob
metadata:
  name: nem2p-job
  namespace: test-deployments
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nem2p-job-container
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["/bin/touch", "foo", "&&", "/bin/date", ">>", "foo", "&&", "/bin/sleep", "60"]
            resources:  
              limits:   
                cpu: "0.5"
                memory: 512Mi
              requests: 
                cpu: "0.5"
                memory: 512Mi
          restartPolicy: OnFailure
#          securityContext:
#            runAsNonRoot: true
#            runAsUser: 889765
#            runAsGroup: 100
      ttlSecondsAfterFinished: 60

# neal: 889765
# gid:  100
# path: /gpfs/gpfs0/project/arcs/nem2p/k8s.log
