apiVersion: v1
kind: Pod
metadata:
  name: nem2p-job
  namespace: test-deployments
spec:
  containers:
  - name: nem2p-job-container
    image: ghcr.io/uvarc/busybox:run-as-user-test
    imagePullPolicy: IfNotPresent
    # command: ["/bin/touch", "foo", "&&", "/bin/date", ">>", "foo", "&&", "/bin/sleep", "60"]
    resources:
      limits: 
        cpu: "0.5"
        memory: 512Mi
      requests:
        cpu: "0.5"
        memory: 512Mi
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: true
    runAsUser: 889765 
    runAsGroup: 100     


# neal: 889765
# gid:  100
# path: /gpfs/gpfs0/project/arcs/nem2p/k8s.log
